### ISSUE TITLE
Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by lionelrudaz** [phosphor-icons/react#45]
Moving from "phosphor-react" to "@phosphor-icons/react", I've got the following issues when deploying on Vercel in a Nextjs application:

```
[Error: EMFILE: too many open files, open '/var/task/node_modules/@phosphor-icons/react/dist/icons/SidebarSimple.es.js'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/var/task/node_modules/@phosphor-icons/react/dist/icons/SidebarSimple.es.js',
  page: '/guides'
}
RequestId: 2c953896-3cf8-4f3a-8bb0-86de2ca6662c Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

I'm still using the /pages directory, haven't moved to /app yet in my codebase.

Tried to upgrade my Node server from v16 to v18, no luck.

SidebarSimple is not even used in my code. 

Looks like it's bugging when I need to check the auth state with NextAuthjs. So perhaps there's a conflict with the signIn and signOut methodes from this other library, as I can see a lot of similar errors in my logs.

Let me know if I can bring more context.

**Comment by TobiasLueger** [comment]
How old is the project and what is the package json look like?☺️

What are you using in the pipe to build the project?

The emfile error sometimes come from a limit at the Node server. So that could be an problem.

**Comment by manskron** [comment]
Having the same problem.

```
Error: EMFILE: too many open files, open '/var/task/node_modules/@phosphor-icons/react/dist/icons/SignIn.es.js'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/var/task/node_modules/@phosphor-icons/react/dist/icons/SignIn.es.js'
}
[Error: EMFILE: too many open files, open '/var/task/node_modules/@phosphor-icons/react/dist/icons/SignIn.es.js'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/var/task/node_modules/@phosphor-icons/react/dist/icons/SignIn.es.js',
  page: '/1'
}
RequestId: f4203201-8c26-4fe8-8812-06219932ddcf Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by TobiasLueger** [comment]
@manskron, could you also give some more informations about your project pls.

How old is the project and what is the package json look like?☺️

What are you using in the pipe to build the project?

**Comment by manskron** [comment]
@TobiasLueger It's a Next.js v13.2.4 project running on Node v18. 
Not entirely sure if this is what you mean, but we don't have a custom build pipe, it's taken care of by the [Next.js compiler](https://nextjs.org/docs/advanced-features/compiler).

**Comment by wfl-junior** [comment]
I am having the same issue, I am trying to use the [modularizeImports](https://nextjs.org/docs/advanced-features/compiler#modularize-imports) feature from next, but then I get the following error: `Module not found: Can't resolve '@phosphor-icons/react/dist/icons/MagnifyingGlass'`, even though typecript says it exists.

**Comment by wfl-junior** [comment]
I managed to solve this problem using the modularizeImports feature from next like mentioned above, but the path for the icons is either incorrect in the `package.json` or for the types in TypeScript.

```json
"exports": {
  ".": {
    "import": "./dist/index.es.js"
  },
  "./*": {
    "import": "./dist/icons/*.es.js"
  }
}
```

![image](https://user-images.githubusercontent.com/61035071/228569781-514576bb-9434-43d4-80fd-f6e471851679.png)


It works with `import Icon from "@phosphor-icons/react/Icon";`

While TypeScript says the path should be `import Icon from "@phosphor-icons/react/dist/icons/Icon";`

![image](https://user-images.githubusercontent.com/61035071/228569634-a54fc0e4-adf5-4554-9a21-ad52fce6b96f.png)

Solution is to add the following property in your next config file:

```js
modularizeImports: {
  "@phosphor-icons/react": {
    transform: "@phosphor-icons/react/{{member}}",
  },
},
```

**Comment by rektdeckard** [comment]
Hey gang. The paths for the icons were correct, but the typings did not account for the aliasing we do in the `exports` field in `package.json`. I have pushed a v2.0.8 build that 1 l. Fixes the typings for aliased exports, and 2. Includes a UMD build and a `main` field, so the lib should be comprehensible to CJS environments.

I recommend using the full /dist/icons/Foo paths all the same, if you plan on using modular imports.

I would love to hear if this fixes things for you.

**Comment by wfl-junior** [comment]
> Hey gang. The paths for the icons were correct, but the typings did not account for the aliasing we do in the `exports` field in `package.json`. I have pushed a v2.0.8 build that
> 
> 1. Fixes the typings for aliased exports, and
> 2. Includes a UMD build and a `main` field, so the lib should be comprehensible to CJS environments.
> 
> I recommend using the full /dist/icons/Foo paths all the same, if you plan on using modular imports.
> 
> I would love to hear if this fixes things for you.

Updated the lib version and my next config to:

```js
modularizeImports: {
  "@phosphor-icons/react": {
    transform: "@phosphor-icons/react/dist/icons/{{member}}",
  },
},
```

And it does indeed work now with this path, thank you!

**Comment by lionelrudaz** [comment]
> It's a Next.js v13.2.4 project running on Node v18.

Same here. I'm also deploying on Vercel.

Sorry for the delay in my answer. 

@rektdeckard, does that mean we must have this configuration if we plan to use the library on a Nextjs project?

```
modularizeImports: {
  "@phosphor-icons/react": {
    transform: "@phosphor-icons/react/dist/icons/{{member}}",
  },
},
```

Please let us know if this is a temporary workaround or something that must be documented for new developers.

**Comment by rektdeckard** [comment]
@lionelrudaz I'm really not sure, I don't use Next and I'm honestly shocked at the hoops library maintainers are now needing to jump through to make basic functionality work in it. Every other build tooling supports tree-shaking of ESM modules out of the box, and can handle this in packages withh10 or 10,000 files. Why not in Next?

**Comment by lionelrudaz** [comment]
Got you, I agree this becomes a nightmare for you.

Should I open an issue at Vercel's end for that or do you plan to document the workaround? With the market shares of Vercel, this is perhaps a good thing to mention somewhere in your pages. I can help for that of course.

**Comment by bernardinorafael** [comment]
Just updating this Issue, I have this same error in a Next.js application, where I have version 2.0.5 of Phosphor and the error still persists, strangely, I have another application published in Vercel with the same version of the package and it does not show error.

**Comment by rektdeckard** [comment]
@bernardinorafael that's because this isn't an error originating in Phosphor, it's a Vercel CLI tool that is not designed to work with libraries with many small files.

Upgrade to 2.0.8 and try modularizing the imports.

**Comment by rektdeckard** [comment]
Possibly resolved by #56. Would anyone here care to test by upgrading to v2.0.10 and attempting to deploy to Vercel?

**Comment by lionelrudaz** [comment]
I've upgraded the library to 2.0.10, was using 2.0.9 before. I wonder if our friends at Vercel haven't changed something at their end, as I haven't added the modularizeImports workaround and I've been deploying with no issue for a while.

Anybody in the same situation?

**Comment by s0urfruit** [comment]
I've tried 2.0.9 & 2.0.10, both still result in the same error:

```
[Error: EMFILE: too many open files, open '/var/task/node_modules/@phosphor-icons/react/dist/icons/SidebarSimple.es.js'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/var/task/node_modules/@phosphor-icons/react/dist/icons/SidebarSimple.es.js',
  page: '/onboard'
}
RequestId: f43037d6-9a55-4320-ac4e-a0c042575b96 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Adding modularizeImports into my `next.config.js` hasn't worked either.

Why has this suddenly become an issue?!

**Comment by s0urfruit** [comment]
New error message on a different route (now errors at Sigma, not Sidebar)

```
[Error: EMFILE: too many open files, open '/var/task/node_modules/@phosphor-icons/react/dist/icons/Sigma.es.js'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/var/task/node_modules/@phosphor-icons/react/dist/icons/Sigma.es.js',
  page: '/dashboard'
}
RequestId: 682253ba-77bf-4251-834d-ade211103887 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by dantevicenzo** [comment]
I'm having the same issue:

```
[Error: EMFILE: too many open files, open '/var/task/node_modules/@phosphor-icons/react/dist/icons/Sigma.es.js'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/var/task/node_modules/@phosphor-icons/react/dist/icons/Sigma.es.js',
  page: '/'
}
RequestId: b2ef59e8-2c97-447d-937b-16b8ecd60b2f Error: Runtime exited with error: exit status 1
Runtime.ExitError
```
i had to switch from `@phospor-icons/react` to `phosphor-react` and now it's working fine.

**Comment by MelkorNemesis** [comment]
Loading the phosphor icons from `react-icons/pi` works ok too.

**Comment by jasondainter** [comment]
Also having this issue on NextJs with Netlify.
Getting

`Jul 11, 12:40:14 AM: 2533ac12 ERROR  [Error: EMFILE: too many open files, open '/var/task/node_modules/@phosphor-icons/react/dist/icons/SidebarSimple.es.js'] {Jul 11, 12:40:14 AM: 2533ac12 ERROR    errno: -24,Jul 11, 12:40:14 AM: 2533ac12 ERROR    code: 'EMFILE',Jul 11, 12:40:14 AM: 2533ac12 ERROR    syscall: 'open',Jul 11, 12:40:14 AM: 2533ac12 ERROR    path: '/var/task/node_modules/@phosphor-icons/react/dist/icons/SidebarSimple.es.js'Jul 11, 12:40:14 AM: 2533ac12 ERROR  }`

@dantevicenzo bit of a noob developer here but your solution looked promising, could you kindly explain the main differences of @phospor-icons/react vs phosphor-react?

I'm importing icons like this if its any help:

`// Import phosphor icons
import {
  PencilLine,
  Balloon,
  HandWaving,
  HandsClapping,
  TreePalm,
  HandsPraying,
  Heart,
  SmileyNervous,
  ThumbsUp,
} from "@phosphor-icons/react";`

Thanks ahead for any help.

**Comment by gabrielvrl** [comment]
Dit not work for me, can anyone help?

**Comment by rektdeckard** [comment]
It looks like Nextjs 13.5 added [optimizations](https://nextjs.org/docs/app/api-reference/next-config-js/optimizePackageImports) specifically for this problem (large component/icon libraries with many files). The `modularizeImports` object is should be replaced with `optimizePackageImports: [...pkg names]`, and the bundler will automagically transform them into the respective submodule imports.

**Comment by xaphod** [comment]
Confirming @rektdeckard's find - we updated to NextJS 13.5.3 and the `modularizeImports` approach wasn't compiling, and we were getting the too many open files crash. The following in next.config.js fixed it:

```
    experimental: { 
      optimizePackageImports: ['@phosphor-icons/react']
    }
```

**Comment by Tamicktom** [comment]
It appears that in Nextjs version 13.5.5 this issue has been resolved without requiring any additional configuration.

**Comment by Kapaak** [comment]
I can confirm that this error is still present, if you try to import more icons at once. 

The modularizeImports fix above is no longer working with the newest version, since the icons are now in different folders 
```@phosphor-icons/react/dist/csr/{{member}}```
and
```@phosphor-icons/react/dist/ssr/{{member}}```

So in order to make it work you also need to change it to this:
```
 modularizeImports: {
    '@phosphor-icons/react': {
      transform: '@phosphor-icons/react/dist/ssr/{{member}}',
    },
  },
```
I was also using styled-components in my code and it was still throwing errors when I tried to style the icons (icon was undefined). So I also had to import the icon this way.
```
import { CaretDown } from '@phosphor-icons/react/dist/ssr/CaretDown';
```

But you would need to import all your icons this way, which is not rly fun. So its easier to use the experimental code and hope that it wont fail.

```
experimental: { 
      optimizePackageImports: ['@phosphor-icons/react']
    }
```

**Comment by conrad-vanl** [comment]
Getting this same error with a Vite + Remix app deployed to vercel. I've determined just importing a single icon causes the EMFILE errors in Vercel. I don't have access to "optimizePackageImports" since this is a remix+vite app. 

I don't have too much helpful to add for others - importing the icons like `import { CaretDown } from "@phosphor-icons/react/dist/csr/CaretDown"` does resolve the issues. So for now we've migrated our codebase to direct imports like this.

**Comment by SamuelMoraR** [comment]
Hello community,

For about two weeks now, I've been experiencing difficulties compiling my Next.js project on Windows 11. Previously, the build process ran smoothly, but now I'm encountering the following error that I can't seem to resolve:

`npm run build

> main-garage@1.1.0 build
> next build

 ✓ Linting and checking validity of types
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Collecting page data
Error: EMFILE: too many open files, open 'C:\....
errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\Users\\....
Generating static pages (69/496) [    ] `

I've reviewed the code changes made, but even switching to a production-ready branch where compilation previously worked fine hasn't resolved the issue. My Windows 11 operating system recently underwent an update, leading me to suspect that something during this update may have affected the compilation process.

Additionally, I am using Next.js version 13.5.6 and Node.js version v22.4.1.

I appreciate any suggestions or advice on how to approach this issue. Has anyone else experienced something similar after updating to Windows 11?

Thank you in advance!

**Comment by nikolailehbrink** [comment]
Hi @rektdeckard, I have the same problem as stated in https://github.com/phosphor-icons/react/issues/45#issuecomment-2082754637. I have a fairly simple remix app, deployed to vercel and every time I try to import the icons with `import { ... } from "@phosphor-icons/react";` the deployed site throws the error mentioned in this issue and the site is down. Now in remix we don't have the option to call `optimizePackageImports`, do you have any idea on how to fix this in a better way, than to importing every icon from their respective path?

**Comment by rektdeckard** [comment]
Just import from the full path instead of the barrel file:

```tsx
import { Smiley } from "@phosphor-icons/react/dist/ssr/Smiley";
```

**Comment by nikolailehbrink** [comment]
> @nikolailehbrink just import from the full path instead of the barrel file:
> 
> ```tsx
> import { Smiley } from "@phosphor-icons/react/dist/ssr/Smiley";
> ```
> 
> Unfortunately there is not a solution on our end. These build tools are simply not equipped for this many files.

Ahh okay, yeah I wondered if there is a different solution, maybe for remix, but I will head over to that repo and ask. Thanks for the icons and packages! @rektdeckard

**Comment by wadefletch** [comment]
Here's a pair of RegExp's for anyone using VSCode to find-and-replace these imports.

Find:
```
import \{ (\w+) \} from "@phosphor-icons/react"
```

Replace:
```
import { $1 } from "@phosphor-icons/react/dist/ssr/$1"
```
